export const SEARCHING = "SEARCHING";
export const DATA_LOADED_LIST_USERS = "DATA_LOADED_LIST_USERS";
export const FETCH_LIST_USERS_PENDING = "FETCH_LIST_USERS_PENDING";
export const FETCH_LIST_USERS_SUCCESS = "FETCH_LIST_USERS_SUCCESS";
export const FETCH_LIST_USERS_FAIL = "FETCH_LIST_USERS_FAIL";
export const DATA_USERS_BY_FILTER = "DATA_USERS_BY_FILTER";
export const DETAIL_USERS_QUESTION = "DETAIL_USERS_QUESTION";
